### PR TITLE
chore(README): slightly adjust README to warn about osko's maturity

### PR DESCRIPTION
**Pull request by fourstepper**

### CODE REVIEW

**Review by Hy3n4 — COMMENTED** [review]
So are we going to use `osko` name all lowercase?

**Comment by fourstepper** [comment]
> So are we going to use `osko` name all lowercase?

Good question, idk... I like it more I think, but I don't really care for either

**Comment by Hy3n4** [comment]
Let's leave this decision for some future us.

**Review by Hy3n4 — APPROVED** [review]
LGTM

**Pull request merged**
