### PR TITLE
feat(dev): create a proper development environment

### PR DESCRIPTION
**Pull request by fourstepper**

### CODE REVIEW

**Comment by fourstepper** [comment]
Actually, we wanted to run all supporting services in the spun up `kind` cluster, right?

Kinda forgot 🤦 Will rewrite and then create some `make` target that will be able to bring both Mimir and Cortex dev environments up and down.

@Hy3n4 if you have any thoughts here, speak your mind, otherwise I'm implementing this tomorrow

**Comment by Hy3n4** [comment]
As far as I remember, we've been considering running Mimir in the cluster, but there may be some reasons to consider why we may not want to do it that way.
- when we start writing the integration tests, we should not rely on running kind (or actually whatever else Kubernetes cluster at all)

Also, we should consider Mimir multitenancy enabled by default or configurable, at least for our case.

**Comment by fourstepper** [comment]
> when we start writing the integration tests, we should not rely on running kind (or actually whatever else Kubernetes cluster at all)

dunno, probably, not sure if that's the topic here

I would say keep multitenancy on by default, as is in the upstream project AFAIK...

**Comment by fourstepper** [comment]
> As far as I remember, we've been considering running Mimir in the cluster, but there may be some reasons to consider why we may not want to do it that way.
> 
> * when we start writing the integration tests, we should not rely on running kind (or actually whatever else Kubernetes cluster at all)
> 
> Also, we should consider Mimir multitenancy enabled by default or configurable, at least for our case.

Hmm, thinking about this again, what do we mean by integration tests? At least for some E2E tests we might wanna rely on KIND anyway? 🤔

**Comment by Hy3n4** [comment]
LGTM from my point of view

**Review by Hy3n4 — APPROVED** [review]

**Pull request merged**
